version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: regtic-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: regtic
