version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    container_name: regtic-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: regtic
