[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"

[[redirects]]
  from = "/api/*"
  to = "https://api.regtic.com/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.dev.environment]
  VUE_APP_API_URL = "https://78pnkdbz8f.execute-api.eu-west-1.amazonaws.com/beta/"
