service: regtic-main-service
# app and org for use with dashboard.serverless.com
#app: regtic-test-app
#org: regtic

provider:
  name: aws
  runtime: nodejs10.x

environment:
  NODE_ENV: development
  REGTIC_DATABASE_URL: postgres://admin:admin@localhost:5432/regtic

functions:
  hellopython:
    runtime: python3.6
    events:
      - http:
          method: get
          path: hellopython
    handler: workers/python-worker.hello
  hellonode:
    runtime: nodejs10.x
    events:
      - http:
          method: get
          path: hellonode
    handler: workers/nodejs-worker.hello

plugins:
    - serverless-offline
