// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// BadCompaniesAllName is an object representing the database table.
type BadCompaniesAllName struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updatedAt" toml:"updatedAt" yaml:"updatedAt"`
	CreatedAt    time.Time   `boil:"created_at" json:"createdAt" toml:"createdAt" yaml:"createdAt"`
	BadCompanyID null.String `boil:"bad_company_id" json:"badCompanyID,omitempty" toml:"badCompanyID" yaml:"badCompanyID,omitempty"`
	Name         string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	NameVector   null.String `boil:"name_vector" json:"nameVector,omitempty" toml:"nameVector" yaml:"nameVector,omitempty"`

	R *badCompaniesAllNameR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L badCompaniesAllNameL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BadCompaniesAllNameColumns = struct {
	ID           string
	UpdatedAt    string
	CreatedAt    string
	BadCompanyID string
	Name         string
	NameVector   string
}{
	ID:           "id",
	UpdatedAt:    "updated_at",
	CreatedAt:    "created_at",
	BadCompanyID: "bad_company_id",
	Name:         "name",
	NameVector:   "name_vector",
}

// Generated where

var BadCompaniesAllNameWhere = struct {
	ID           whereHelperstring
	UpdatedAt    whereHelpertime_Time
	CreatedAt    whereHelpertime_Time
	BadCompanyID whereHelpernull_String
	Name         whereHelperstring
	NameVector   whereHelpernull_String
}{
	ID:           whereHelperstring{field: "\"bad_companies_all_names\".\"id\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"bad_companies_all_names\".\"updated_at\""},
	CreatedAt:    whereHelpertime_Time{field: "\"bad_companies_all_names\".\"created_at\""},
	BadCompanyID: whereHelpernull_String{field: "\"bad_companies_all_names\".\"bad_company_id\""},
	Name:         whereHelperstring{field: "\"bad_companies_all_names\".\"name\""},
	NameVector:   whereHelpernull_String{field: "\"bad_companies_all_names\".\"name_vector\""},
}

// BadCompaniesAllNameRels is where relationship names are stored.
var BadCompaniesAllNameRels = struct {
	BadCompany string
}{
	BadCompany: "BadCompany",
}

// badCompaniesAllNameR is where relationships are stored.
type badCompaniesAllNameR struct {
	BadCompany *BadCompany
}

// NewStruct creates a new relationship struct
func (*badCompaniesAllNameR) NewStruct() *badCompaniesAllNameR {
	return &badCompaniesAllNameR{}
}

// badCompaniesAllNameL is where Load methods for each relationship are stored.
type badCompaniesAllNameL struct{}

var (
	badCompaniesAllNameAllColumns            = []string{"id", "updated_at", "created_at", "bad_company_id", "name", "name_vector"}
	badCompaniesAllNameColumnsWithoutDefault = []string{"bad_company_id", "name", "name_vector"}
	badCompaniesAllNameColumnsWithDefault    = []string{"id", "updated_at", "created_at"}
	badCompaniesAllNamePrimaryKeyColumns     = []string{"id"}
)

type (
	// BadCompaniesAllNameSlice is an alias for a slice of pointers to BadCompaniesAllName.
	// This should generally be used opposed to []BadCompaniesAllName.
	BadCompaniesAllNameSlice []*BadCompaniesAllName

	badCompaniesAllNameQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	badCompaniesAllNameType                 = reflect.TypeOf(&BadCompaniesAllName{})
	badCompaniesAllNameMapping              = queries.MakeStructMapping(badCompaniesAllNameType)
	badCompaniesAllNamePrimaryKeyMapping, _ = queries.BindMapping(badCompaniesAllNameType, badCompaniesAllNameMapping, badCompaniesAllNamePrimaryKeyColumns)
	badCompaniesAllNameInsertCacheMut       sync.RWMutex
	badCompaniesAllNameInsertCache          = make(map[string]insertCache)
	badCompaniesAllNameUpdateCacheMut       sync.RWMutex
	badCompaniesAllNameUpdateCache          = make(map[string]updateCache)
	badCompaniesAllNameUpsertCacheMut       sync.RWMutex
	badCompaniesAllNameUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single badCompaniesAllName record from the query.
func (q badCompaniesAllNameQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BadCompaniesAllName, error) {
	o := &BadCompaniesAllName{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bad_companies_all_names")
	}

	return o, nil
}

// All returns all BadCompaniesAllName records from the query.
func (q badCompaniesAllNameQuery) All(ctx context.Context, exec boil.ContextExecutor) (BadCompaniesAllNameSlice, error) {
	var o []*BadCompaniesAllName

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BadCompaniesAllName slice")
	}

	return o, nil
}

// Count returns the count of all BadCompaniesAllName records in the query.
func (q badCompaniesAllNameQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bad_companies_all_names rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q badCompaniesAllNameQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bad_companies_all_names exists")
	}

	return count > 0, nil
}

// BadCompany pointed to by the foreign key.
func (o *BadCompaniesAllName) BadCompany(mods ...qm.QueryMod) badCompanyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.BadCompanyID),
	}

	queryMods = append(queryMods, mods...)

	query := BadCompanies(queryMods...)
	queries.SetFrom(query.Query, "\"bad_companies\"")

	return query
}

// LoadBadCompany allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (badCompaniesAllNameL) LoadBadCompany(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBadCompaniesAllName interface{}, mods queries.Applicator) error {
	var slice []*BadCompaniesAllName
	var object *BadCompaniesAllName

	if singular {
		object = maybeBadCompaniesAllName.(*BadCompaniesAllName)
	} else {
		slice = *maybeBadCompaniesAllName.(*[]*BadCompaniesAllName)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &badCompaniesAllNameR{}
		}
		if !queries.IsNil(object.BadCompanyID) {
			args = append(args, object.BadCompanyID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &badCompaniesAllNameR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.BadCompanyID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.BadCompanyID) {
				args = append(args, obj.BadCompanyID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`bad_companies`), qm.WhereIn(`bad_companies.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load BadCompany")
	}

	var resultSlice []*BadCompany
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice BadCompany")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for bad_companies")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for bad_companies")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.BadCompany = foreign
		if foreign.R == nil {
			foreign.R = &badCompanyR{}
		}
		foreign.R.BadCompaniesAllNames = append(foreign.R.BadCompaniesAllNames, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.BadCompanyID, foreign.ID) {
				local.R.BadCompany = foreign
				if foreign.R == nil {
					foreign.R = &badCompanyR{}
				}
				foreign.R.BadCompaniesAllNames = append(foreign.R.BadCompaniesAllNames, local)
				break
			}
		}
	}

	return nil
}

// SetBadCompany of the badCompaniesAllName to the related item.
// Sets o.R.BadCompany to related.
// Adds o to related.R.BadCompaniesAllNames.
func (o *BadCompaniesAllName) SetBadCompany(ctx context.Context, exec boil.ContextExecutor, insert bool, related *BadCompany) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"bad_companies_all_names\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"bad_company_id"}),
		strmangle.WhereClause("\"", "\"", 2, badCompaniesAllNamePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.BadCompanyID, related.ID)
	if o.R == nil {
		o.R = &badCompaniesAllNameR{
			BadCompany: related,
		}
	} else {
		o.R.BadCompany = related
	}

	if related.R == nil {
		related.R = &badCompanyR{
			BadCompaniesAllNames: BadCompaniesAllNameSlice{o},
		}
	} else {
		related.R.BadCompaniesAllNames = append(related.R.BadCompaniesAllNames, o)
	}

	return nil
}

// RemoveBadCompany relationship.
// Sets o.R.BadCompany to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *BadCompaniesAllName) RemoveBadCompany(ctx context.Context, exec boil.ContextExecutor, related *BadCompany) error {
	var err error

	queries.SetScanner(&o.BadCompanyID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("bad_company_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.BadCompany = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.BadCompaniesAllNames {
		if queries.Equal(o.BadCompanyID, ri.BadCompanyID) {
			continue
		}

		ln := len(related.R.BadCompaniesAllNames)
		if ln > 1 && i < ln-1 {
			related.R.BadCompaniesAllNames[i] = related.R.BadCompaniesAllNames[ln-1]
		}
		related.R.BadCompaniesAllNames = related.R.BadCompaniesAllNames[:ln-1]
		break
	}
	return nil
}

// BadCompaniesAllNames retrieves all the records using an executor.
func BadCompaniesAllNames(mods ...qm.QueryMod) badCompaniesAllNameQuery {
	mods = append(mods, qm.From("\"bad_companies_all_names\""))
	return badCompaniesAllNameQuery{NewQuery(mods...)}
}

// FindBadCompaniesAllName retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBadCompaniesAllName(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*BadCompaniesAllName, error) {
	badCompaniesAllNameObj := &BadCompaniesAllName{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"bad_companies_all_names\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, badCompaniesAllNameObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bad_companies_all_names")
	}

	return badCompaniesAllNameObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BadCompaniesAllName) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bad_companies_all_names provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(badCompaniesAllNameColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	badCompaniesAllNameInsertCacheMut.RLock()
	cache, cached := badCompaniesAllNameInsertCache[key]
	badCompaniesAllNameInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			badCompaniesAllNameAllColumns,
			badCompaniesAllNameColumnsWithDefault,
			badCompaniesAllNameColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(badCompaniesAllNameType, badCompaniesAllNameMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(badCompaniesAllNameType, badCompaniesAllNameMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"bad_companies_all_names\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"bad_companies_all_names\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bad_companies_all_names")
	}

	if !cached {
		badCompaniesAllNameInsertCacheMut.Lock()
		badCompaniesAllNameInsertCache[key] = cache
		badCompaniesAllNameInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the BadCompaniesAllName.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BadCompaniesAllName) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	badCompaniesAllNameUpdateCacheMut.RLock()
	cache, cached := badCompaniesAllNameUpdateCache[key]
	badCompaniesAllNameUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			badCompaniesAllNameAllColumns,
			badCompaniesAllNamePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update bad_companies_all_names, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"bad_companies_all_names\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, badCompaniesAllNamePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(badCompaniesAllNameType, badCompaniesAllNameMapping, append(wl, badCompaniesAllNamePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update bad_companies_all_names row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for bad_companies_all_names")
	}

	if !cached {
		badCompaniesAllNameUpdateCacheMut.Lock()
		badCompaniesAllNameUpdateCache[key] = cache
		badCompaniesAllNameUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q badCompaniesAllNameQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for bad_companies_all_names")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for bad_companies_all_names")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BadCompaniesAllNameSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), badCompaniesAllNamePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"bad_companies_all_names\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, badCompaniesAllNamePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in badCompaniesAllName slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all badCompaniesAllName")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BadCompaniesAllName) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bad_companies_all_names provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(badCompaniesAllNameColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	badCompaniesAllNameUpsertCacheMut.RLock()
	cache, cached := badCompaniesAllNameUpsertCache[key]
	badCompaniesAllNameUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			badCompaniesAllNameAllColumns,
			badCompaniesAllNameColumnsWithDefault,
			badCompaniesAllNameColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			badCompaniesAllNameAllColumns,
			badCompaniesAllNamePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert bad_companies_all_names, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(badCompaniesAllNamePrimaryKeyColumns))
			copy(conflict, badCompaniesAllNamePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"bad_companies_all_names\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(badCompaniesAllNameType, badCompaniesAllNameMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(badCompaniesAllNameType, badCompaniesAllNameMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert bad_companies_all_names")
	}

	if !cached {
		badCompaniesAllNameUpsertCacheMut.Lock()
		badCompaniesAllNameUpsertCache[key] = cache
		badCompaniesAllNameUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single BadCompaniesAllName record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BadCompaniesAllName) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BadCompaniesAllName provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), badCompaniesAllNamePrimaryKeyMapping)
	sql := "DELETE FROM \"bad_companies_all_names\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from bad_companies_all_names")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for bad_companies_all_names")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q badCompaniesAllNameQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no badCompaniesAllNameQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bad_companies_all_names")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bad_companies_all_names")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BadCompaniesAllNameSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), badCompaniesAllNamePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"bad_companies_all_names\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, badCompaniesAllNamePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from badCompaniesAllName slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bad_companies_all_names")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BadCompaniesAllName) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBadCompaniesAllName(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BadCompaniesAllNameSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BadCompaniesAllNameSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), badCompaniesAllNamePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"bad_companies_all_names\".* FROM \"bad_companies_all_names\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, badCompaniesAllNamePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BadCompaniesAllNameSlice")
	}

	*o = slice

	return nil
}

// BadCompaniesAllNameExists checks if the BadCompaniesAllName row exists.
func BadCompaniesAllNameExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"bad_companies_all_names\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bad_companies_all_names exists")
	}

	return exists, nil
}
