// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BadPersons        string
	BadPersonsAliases string
	Companies         string
	CompanyToCompany  string
	CompanyToPerson   string
	Persons           string
}{
	BadPersons:        "bad_persons",
	BadPersonsAliases: "bad_persons_aliases",
	Companies:         "companies",
	CompanyToCompany:  "company_to_company",
	CompanyToPerson:   "company_to_person",
	Persons:           "persons",
}
