// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("BadPersons", testBadPersons)
	t.Run("BadPersonsAliases", testBadPersonsAliases)
	t.Run("Companies", testCompanies)
	t.Run("Persons", testPersons)
}

func TestDelete(t *testing.T) {
	t.Run("BadPersons", testBadPersonsDelete)
	t.Run("BadPersonsAliases", testBadPersonsAliasesDelete)
	t.Run("Companies", testCompaniesDelete)
	t.Run("Persons", testPersonsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("BadPersons", testBadPersonsQueryDeleteAll)
	t.Run("BadPersonsAliases", testBadPersonsAliasesQueryDeleteAll)
	t.Run("Companies", testCompaniesQueryDeleteAll)
	t.Run("Persons", testPersonsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("BadPersons", testBadPersonsSliceDeleteAll)
	t.Run("BadPersonsAliases", testBadPersonsAliasesSliceDeleteAll)
	t.Run("Companies", testCompaniesSliceDeleteAll)
	t.Run("Persons", testPersonsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("BadPersons", testBadPersonsExists)
	t.Run("BadPersonsAliases", testBadPersonsAliasesExists)
	t.Run("Companies", testCompaniesExists)
	t.Run("Persons", testPersonsExists)
}

func TestFind(t *testing.T) {
	t.Run("BadPersons", testBadPersonsFind)
	t.Run("BadPersonsAliases", testBadPersonsAliasesFind)
	t.Run("Companies", testCompaniesFind)
	t.Run("Persons", testPersonsFind)
}

func TestBind(t *testing.T) {
	t.Run("BadPersons", testBadPersonsBind)
	t.Run("BadPersonsAliases", testBadPersonsAliasesBind)
	t.Run("Companies", testCompaniesBind)
	t.Run("Persons", testPersonsBind)
}

func TestOne(t *testing.T) {
	t.Run("BadPersons", testBadPersonsOne)
	t.Run("BadPersonsAliases", testBadPersonsAliasesOne)
	t.Run("Companies", testCompaniesOne)
	t.Run("Persons", testPersonsOne)
}

func TestAll(t *testing.T) {
	t.Run("BadPersons", testBadPersonsAll)
	t.Run("BadPersonsAliases", testBadPersonsAliasesAll)
	t.Run("Companies", testCompaniesAll)
	t.Run("Persons", testPersonsAll)
}

func TestCount(t *testing.T) {
	t.Run("BadPersons", testBadPersonsCount)
	t.Run("BadPersonsAliases", testBadPersonsAliasesCount)
	t.Run("Companies", testCompaniesCount)
	t.Run("Persons", testPersonsCount)
}

func TestInsert(t *testing.T) {
	t.Run("BadPersons", testBadPersonsInsert)
	t.Run("BadPersons", testBadPersonsInsertWhitelist)
	t.Run("BadPersonsAliases", testBadPersonsAliasesInsert)
	t.Run("BadPersonsAliases", testBadPersonsAliasesInsertWhitelist)
	t.Run("Companies", testCompaniesInsert)
	t.Run("Companies", testCompaniesInsertWhitelist)
	t.Run("Persons", testPersonsInsert)
	t.Run("Persons", testPersonsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BadPersonsAliasToBadPersonUsingBadPerson", testBadPersonsAliasToOneBadPersonUsingBadPerson)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("BadPersonToBadPersonsAliases", testBadPersonToManyBadPersonsAliases)
	t.Run("CompanyToMotherCompanyCompanies", testCompanyToManyMotherCompanyCompanies)
	t.Run("CompanyToDaughterCompanyCompanies", testCompanyToManyDaughterCompanyCompanies)
	t.Run("CompanyToPersons", testCompanyToManyPersons)
	t.Run("PersonToCompanies", testPersonToManyCompanies)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BadPersonsAliasToBadPersonUsingBadPersonsAliases", testBadPersonsAliasToOneSetOpBadPersonUsingBadPerson)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("BadPersonToBadPersonsAliases", testBadPersonToManyAddOpBadPersonsAliases)
	t.Run("CompanyToMotherCompanyCompanies", testCompanyToManyAddOpMotherCompanyCompanies)
	t.Run("CompanyToDaughterCompanyCompanies", testCompanyToManyAddOpDaughterCompanyCompanies)
	t.Run("CompanyToPersons", testCompanyToManyAddOpPersons)
	t.Run("PersonToCompanies", testPersonToManyAddOpCompanies)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("CompanyToMotherCompanyCompanies", testCompanyToManySetOpMotherCompanyCompanies)
	t.Run("CompanyToDaughterCompanyCompanies", testCompanyToManySetOpDaughterCompanyCompanies)
	t.Run("CompanyToPersons", testCompanyToManySetOpPersons)
	t.Run("PersonToCompanies", testPersonToManySetOpCompanies)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("CompanyToMotherCompanyCompanies", testCompanyToManyRemoveOpMotherCompanyCompanies)
	t.Run("CompanyToDaughterCompanyCompanies", testCompanyToManyRemoveOpDaughterCompanyCompanies)
	t.Run("CompanyToPersons", testCompanyToManyRemoveOpPersons)
	t.Run("PersonToCompanies", testPersonToManyRemoveOpCompanies)
}

func TestReload(t *testing.T) {
	t.Run("BadPersons", testBadPersonsReload)
	t.Run("BadPersonsAliases", testBadPersonsAliasesReload)
	t.Run("Companies", testCompaniesReload)
	t.Run("Persons", testPersonsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("BadPersons", testBadPersonsReloadAll)
	t.Run("BadPersonsAliases", testBadPersonsAliasesReloadAll)
	t.Run("Companies", testCompaniesReloadAll)
	t.Run("Persons", testPersonsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("BadPersons", testBadPersonsSelect)
	t.Run("BadPersonsAliases", testBadPersonsAliasesSelect)
	t.Run("Companies", testCompaniesSelect)
	t.Run("Persons", testPersonsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("BadPersons", testBadPersonsUpdate)
	t.Run("BadPersonsAliases", testBadPersonsAliasesUpdate)
	t.Run("Companies", testCompaniesUpdate)
	t.Run("Persons", testPersonsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("BadPersons", testBadPersonsSliceUpdateAll)
	t.Run("BadPersonsAliases", testBadPersonsAliasesSliceUpdateAll)
	t.Run("Companies", testCompaniesSliceUpdateAll)
	t.Run("Persons", testPersonsSliceUpdateAll)
}
