// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BadCompanies", testBadCompaniesUpsert)

	t.Run("BadCompaniesAddresses", testBadCompaniesAddressesUpsert)

	t.Run("BadCompaniesAllNames", testBadCompaniesAllNamesUpsert)

	t.Run("BadPersons", testBadPersonsUpsert)

	t.Run("BadPersonsAddresses", testBadPersonsAddressesUpsert)

	t.Run("BadPersonsAllNames", testBadPersonsAllNamesUpsert)

	t.Run("Companies", testCompaniesUpsert)

	t.Run("CompanyToCompanies", testCompanyToCompaniesUpsert)

	t.Run("CompanyToPeople", testCompanyToPeopleUpsert)

	t.Run("Persons", testPersonsUpsert)
}
