AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Globals:
  Function:
    Timeout: 1500
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'http://localhost:8080'"
Resources:
  FindCompanies:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/main
      Runtime: go1.x
      Environment:
        Variables:
          ORIGIN: "http://localhost:8080"
          REGTIC_DATABASE_URL: "postgres://admin:admin@localhost:5432/regtic?sslmode=disable"
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /v1/find_companies
            Method: get
  ValidateCompany:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/main
      Runtime: go1.x
      Environment:
        Variables:
          ORIGIN: "http://localhost:8080"
          REGTIC_DATABASE_URL: "postgres://admin:admin@localhost:5432/regtic?sslmode=disable"
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /v1/validate_company
            Method: get
